import type { NextPage } from "next";
import Head from "next/head";
import { DataGrid } from "@mui/x-data-grid";

import {
  AuthAction,
  withAuthUser,
  withAuthUserTokenSSR,
} from "next-firebase-auth";

import styles from "../styles/Home.module.css";
import { useFetchOnLoad } from "../services/hooks";
import { usersApi } from "../services/users";

const columns = [
  { field: "uid", headerName: "UID", width: 200 },
  { field: "displayName", headerName: "Name", width: 200 },
  { field: "email", headerName: "Email", width: 200 },
];
const Users: any = () => {
  const { data, loading, error } = useFetchOnLoad(usersApi);
  const users = data?.users;

  return (
    <div className={styles.container}>
      <Head>
        <title>Spotifiuby - Back Office</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2>Welcome to the Users Page</h2>

        {loading ? (
          <p>Loading</p>
        ) : error ? (
          <p>Error</p>
        ) : (
          <DataGrid
            className="w80"
            rows={users}
            columns={columns}
            pageSize={10}
            rowsPerPageOptions={[5, 10, 50, 100]}
            getRowId={(row) => row.uid}
          />
        )}
      </main>
    </div>
  );
};

export const getServerSideProps = withAuthUserTokenSSR({
  whenUnauthed: AuthAction.REDIRECT_TO_LOGIN,
})();

export default withAuthUser({
  whenUnauthedAfterInit: AuthAction.REDIRECT_TO_LOGIN,
})(Users);
